spring:
  application:
    name: digital-registered-letter
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
logging:
  level:
    root: INFO
integration:
  party:
    connectTimeout: 5
    readTimeout: 30
